[DEFAULT]
PRODUCT_COMPONENT = deploy
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${ENVIRONMENT}
AUTO_DEPLOY = false
SLACK_DEPLOY_NOTIFICATION = false
SLACK_CHANNEL = deployments

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${CLEAN_BRANCH}
SLACK_DEPLOY_NOTIFICATION = true
SLACK_CHANNEL = zabbix-userdetails
AUTO_DEPLOY = false

HOSTED_ZONE = dev.ala.org.au
SUB_DOMAIN = $PRODUCT_NAME-$CLEAN_BRANCH

[testing]
HOSTED_ZONE = test.ala.org.au
SUB_DOMAIN = $PRODUCT_NAME

[staging]
HOSTED_ZONE = ala.org.au
SUB_DOMAIN = $PRODUCT_NAME-staging

[production]
HOSTED_ZONE = ala.org.au
SUB_DOMAIN = $PRODUCT_NAME
