[DEFAULT]
###
# pipeline vars
PRODUCT_COMPONENT = deploy
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${ENVIRONMENT}
AUTO_DEPLOY = true
SLACK_DEPLOY_NOTIFICATION = false
SLACK_CHANNEL = deployments

###
# application vars
AUTH_HOSTS =
  aws-auth-cognito-dev-0.dev.ala.org.au
DATA_DIR = /data
USER_DETAILS_VERSION = 4.0.0-SNAPSHOT
USERDETAILS_BACKEND = cognito

USERDETAILS_HOST_NAME = auth-cognito.dev.ala.org.au
OIDC_DISCOVERY_URI = https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_pQUl30qBX/.well-known/openid-configuration
USERDETAILS_OIDC_LOGOUTURL = https://auth-secure-development.auth.ap-southeast-2.amazoncognito.com/logout
USE_OPENJDK8 = false
USE_OPENJDK11 = true

AUTH_BASE_URL = https://auth-dev.ala.org.au
AUTH_CAS_URL = https://auth-dev.ala.org.au/cas
SIGHTINGS_BASE_URL = https://biocollect-test.ala.org.au/spotter
SPATIAL_BASE_URL = https://spatial.ala.org.au
VOLUNTEER_BASE_URL = https://volunteer.ala.org.au
LISTS_BASE_URL = https://lists.ala.org.au
BIOCACHE_BASE_URL = https://biocache.ala.org.au
ALERTS_BASE_URL = https://alerts.ala.org.au
ALA_BASE_URL = https://www.ala.org.au
ALA_LOGO_URL = https://www.ala.org.au/app/uploads/2020/06/ALA_Logo_Inline_RGB-300x63.png
TERMS_URL = https://www.ala.org.au/terms-of-use/
BIE_BASE_URL =  https://bie.ala.org.au
SANDBOX_BASE_URL =  https://sandbox.ala.org.au
DEFAULT_LOGOUT_REDIRECT_URL = https://www-test.ala.org.au
SKIN_FLUID_LAYOUT = true

#
# SSL Configuration files
#
WEBSERVER_NGINX = true
SSL = true
SSL_CERTIFICATE_SERVER_DIR = /etc/sslmate
SSL_CERT_FILE = '*.ala.org.au.chained.crt'
SSL_KEY_FILE = '*.ala.org.au.key'
SSL_CHAIN_FILE = '*.ala.org.au.chain.crt'
FORCE_HTTPS = true
# disable as we have multiple apps/deploys sharing this hostname
#NGINX_VHOST_FRAGMENTS_TO_CLEAR:
#- "nectar-auth-dev-2021.ala.org.au"
# AWS_ELB_HEALTHCHECK_DEFAULT = true
NGINX_VHOST_FRAGMENTS_TO_CLEAR_NO_WARNING = true
NGINX_DEFAULT_VHOST_REQUIRED = true
# NGINX_SET_REAL_IPS:
# - "172.30.0.0/16"


# Elasticache Spring session Configuration
SPRING_SESSION_STORE_TYPE = none

AUTH_COOKIE_NAME = ALA-Auth-Dev
AUTH_COOKIE_ENABLED = true
AUTH_COOKIE_DOMAIN = .ala.org.au

# automatic registration ALA user password
#USER_CREATE_PASSWORD = "stored in AWS Secrets Manager"

USERDETAILS_HOSTNAME = ${USERDETAILS_HOST_NAME}
USERDETAILS_URL = https://${USERDETAILS_HOST_NAME}/userdetails
USERDETAILS_BASE_URL = https://${USERDETAILS_HOST_NAME}
USERDETAILS_SERVER_NAME = https://${USERDETAILS_HOST_NAME}
USERDETAILS_CONTEXT_PATH = userdetails
USERDETAILS_BOOTADMIN_CLIENT_NAME = "User Details Dev"
USERDETAILS_USE_CAS = false
USERDETAILS_USE_OIDC = true
USERDETAILS_OIDC_CLIENT_ID = 4rho5gjgpb4gk00mhnsf6i64j8
#USERDETAILS_OIDC_SECRET = "stored in AWS Secrets Manager"
USERDETAILS_OIDC_DISCOVERY_URI = https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_pQUl30qBX/.well-known/openid-configuration

USERDETAILS_JWT_ENABLED = true
USERDETAILS_JWT_FALLBACK_TO_LEGACY = true
USERDETAILS_ENDPOINT_USER = admin
#USERDETAILS_ENDPOINT_PASSWORD = "stored in AWS Secrets Manager"
USERDETAILS_RECAPTCHA_SITE_KEY = 6LcEpjglAAAAACBuI1AZ4CkJ4-NbxojpA7NaAgNN
#USERDETAILS_RECAPTCHA_SECRET_KEY = "stored in AWS Secrets Manager"
OAUTH_PROVIDERS_FLICKR_ENABLED = true
OAUTH_PROVIDERS_FLICKR_KEY = 4e53956eac74ec2d14b40dd0291e630e
#OAUTH_PROVIDERS_FLICKR_SECRET =  "stored in AWS Secrets Manager"
GRAILS_SERVER_URL = https://grails.dev.ala.org.au
OAUTH_PROVIDERS_FLICKR_CALLBACK = ${GRAILS_SERVER_URL}/profile/flickrCallback
OAUTH_PROVIDERS_INATURALIST_ENABLED = true
OAUTH_PROVIDERS_INATURALIST_KEY = 0f8d35e6bb4d612531b3535be3b42d1462564ceeb37e9fd44186361920f71650
#OAUTH_PROVIDERS_INATURALIST_SECRET = "stored in AWS Secrets Manager"
OAUTH_PROVIDERS_INATURALIST_CALLBACK = ${GRAILS_SERVER_URL}/profile/inaturalistCallback
USER_STORE_DB_ENCODER = bcrypt
USER_STORE_DB_BCRYPT_STRENGTH = 10
USER_STORE_DB_ENCODING_SALT = nXg798dr60987Hgb
USER_STORE_DB_ENCODING_ALGORITHM = MD5

# values for displaying extra information on registration
SHOW_ALA_SURVEY = true
AFFILIATION_SURVEY = true
SHOW_ALA_MESSAGE = true
SHOW_AUTHORISED_SYSTEM = false
RESET_PASSWORD_ARTICLE = https://support.ala.org.au/support/solutions/articles/6000194958-my-username-password-isn-t-working-or-i-can-t-remember-my-username-password
ALERT_ARTICLE = https://support.ala.org.au/support/solutions/articles/6000195858-how-do-i-manage-email-alerts-from-the-ala
ACTIVATION_ARTICLE = https://support.ala.org.au/support/solutions/articles/6000195196-i-created-an-account-but-did-not-receive-the-account-activation-email

BOOTADMIN_ENABLED = false

COGNITO_REGION = ap-southeast-2
COGNITO_POOLID = ap-southeast-2_pQUl30qBX
#COGNITO_ACCESSKEY = "stored in AWS Secrets Manager"
#COGNITO_SECRETKEY = "stored in AWS Secrets Manager"

HEADER_AND_FOOTER_BASEURL = https://www-dev.ala.org.au/commonui-bs3-2019
HEADER_AND_FOOTER_VERSION = 2

SECURITY_CORE_ROLEATTRIBUTE = ala:role
SECURITY_JWT_ROLEATTRIBUTES = cognito:groups
SECURITY_JWT_ROLESFROMACCESSTOKEN = true
SECURITY_OIDC_LOGOUTACTION = cognito
SECURITY_JWT_USERIDCLAIM = username
SECURITY_JWT_ROLECLAIMS = cognito:groups

ENABLED_AUTHORISED_SYSTEMS = true
ENABLED_BULKCREATE = false
ENABLED_EXPORTUSERS = false

OPENAPI_SERVER_URLS = https://api.test.ala.org.au/userdetails/cognito/dev
OPENAPI_OAUTH_URL = https://auth-secure-development.auth.ap-southeast-2.amazoncognito.com/oauth2

GATEWAY_USAGEPLANID = yuz7fr
DYNAMIC_CLIENT_REGISTRATION = true
DYNAMIC_CLIENT_SCOPES = 
  "email",
  "openid",
  "profile",
  "ala/attrs",
  "ala/roles"
DYNAMIC_CLIENT_GALAH_CALLBACKURLS = 
  "http://localhost:1410",
  "http://localhost:1410/",
  "http://localhost:1410/*"
DYNAMIC_CLIENT_TOKENS_CALLBACKURLS = "https://tokens.test.ala.org.au/login"
TOKENAPP_URL =  https://tokens.test.ala.org.au/token
DOCSPORTAL_URL = https://docs.dev.ala.org.au/#introduction
USERS_DELEGATED_GROUP_NAMES = 
  'ap-southeast-2_pQUl30qBX_AAF',
  'ap-southeast-2_pQUl30qBX_Facebook',
  'ap-southeast-2_pQUl30qBX_Google',
  'ap-southeast-2_pQUl30qBX_SignInWithApple'
APIKEY_TYPE = aws
DYNAMODBTABLENAME = UserApplications-development
DYNAMODBTABLE_DYNAMODBPK = userId
DYNAMODBTABLE_DYNAMODBSK = clientId
AFFILIATION_SURVEY_ENABLED = true

USERDETAILS_WEB_URL = https://${USERDETAILS_HOST_NAME}/userdetails/
USERDETAILS_API_URL = https://api.test.ala.org.au/userdetailscognitodev/

USERDETAILS_JWT_CLIENT_ENABLED = true
USERDETAILS_JWT_SCOPES = users/read
USERDETAILS_JWT_CLIENTID = 6bvhm2m2kmqte1lmso3vgiqqjc
#USERDETAILS_JWT_SECRET = "stored in AWS Secrets Manager"

# This should be false after bulk user upload
USERDETAILS_API_USEGATEWAYAPI = true

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${CLEAN_BRANCH}
SLACK_CHANNEL = zabbix-userdetails

HOSTED_ZONE = dev.ala.org.au
SUB_DOMAIN = ${PRODUCT_NAME}-${CLEAN_BRANCH}

[testing]
HOSTED_ZONE = test.ala.org.au
SUB_DOMAIN = ${PRODUCT_NAME}

[staging]
HOSTED_ZONE = ala.org.au
SUB_DOMAIN = ${PRODUCT_NAME}-staging

[production]
HOSTED_ZONE = ala.org.au
SUB_DOMAIN = ${PRODUCT_NAME}
AUTO_DEPLOY = false
SLACK_DEPLOY_NOTIFICATION = true