pluginManagement {
    repositories {
        mavenLocal()
        maven { url "https://nexus.ala.org.au/content/groups/public/" }
        maven { url "https://repo.grails.org/grails/core" }
        gradlePluginPortal()
    }

    plugins {
        id "org.grails.grails-gradle-plugin" version "6.1.2"
        id "org.grails.grails-web" version "6.1.2"
        id "org.grails.grails-gsp" version "6.1.2"
        id "com.bertramlabs.asset-pipeline" version "4.3.0"
        id "org.grails.grails-plugin" version "2.0.13"
    }
}

rootProject.name='userdetails-project'
include 'userdetails-plugin'
include 'userdetails-cognito'
include 'userdetails-gorm'
