AWSTemplateFormatVersion: '2010-09-09'

Description: Base resources for the Userdetails service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production

Resources:

  UserdetailsRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: !If [ NotProd, true, false ]
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub
                         - userdetails-${ResourceName}
                         - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicPull
            Effect: Allow
            Principal: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
      Tags:
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Branch
          Value: !Ref pCleanBranch

  UserdetailsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub 
              - userdetails-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: !Sub Userdetails app ${pEnvironment} secrets


Outputs:

  UserdetailsRepositoryArn:
    Description: The ECR repository ARN for the userdetails service
    Value: !GetAtt UserdetailsRepository.Arn

  UserdetailsRepositoryName:
    Description: The ECR repository ARN for the userdetails service
    Value: !Ref UserdetailsRepository

  UserdetailsSecret:
    Description: The Secrets name for userdetails
    Value: !Ref UserdetailsSecret