AWSTemplateFormatVersion: '2010-09-09'

Description: Base resources for the Userdetails service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
#  pEksClusterId:
#    Type: String
#    Description: The EKS cluster id
#  pProductName:
#    Type: String
#    Description: The name of the product
#  pServiceAccountName:
#    Type: String
#    Description: The name of the service account

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production

Resources:

  UserdetailsRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: !If [ NotProd, true, false ]
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub
                         - userdetails-${ResourceName}
                         - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicPull
            Effect: Allow
            Principal: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
      Tags:
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Branch
          Value: !Ref pCleanBranch

  UserdetailsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub 
              - userdetails-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      Description: !Sub Userdetails app ${pEnvironment} secrets

  UserdetailsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Permissions to deploy userdetails
      ManagedPolicyName: !Sub 
                           - userdetails-policy-${ResourceName}
                           - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendTemplatedEmail
              - ses:SendRawEmail
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - apigateway:POST
              - apigateway:GET
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:UpdateTimeToLive
              - dynamodb:ConditionCheckItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:Scan
              - dynamodb:ListTagsOfResource
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:DescribeTimeToLive
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UserApplications*/index/*
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UserApplications*
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UserApplications*/stream/*
      Roles:
        - !Ref UserdetailsRole

  UserdetailsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
                  - userdetails-role-${ResourceName}
                  - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/E2B4E818912ED7B145C9B4AA0B8D83A8
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                oidc.eks.ap-southeast-2.amazonaws.com/id/E2B4E818912ED7B145C9B4AA0B8D83A8:sub: "system:serviceaccount:userdetails:userdetails-service-account"
                eks.amazonaws.com:aud: "sts.amazonaws.com"
#      AssumeRolePolicyDocument: !Sub
#        - |
#          {
#            "Version": "2012-10-17",
#            "Statement": [
#                {
#                    "Effect": "Allow",
#                    "Principal": {
#                        "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${pEksClusterId}"
#                    },
#                    "Action": "sts:AssumeRoleWithWebIdentity",
#                    "Condition": {
#                        "StringEquals": {
#                            "${OidcProviderEndpoint}:sub": "system:serviceaccount:${pProductName}:${pServiceAccountName}"
#                        }
#                    }
#                }
#            ]
#          }
#        -
#          pEksClusterId: !Ref pEksClusterId
#          OidcProviderEndpoint: !Sub oidc.eks.${AWS::Region}.amazonaws.com/id/${pEksClusterId}
#          pProductName: !Ref pProductName
#          pServiceAccountName: !Ref pServiceAccountName
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser


Outputs:

  UserdetailsRepositoryArn:
    Description: The ECR repository ARN for the userdetails service
    Value: !GetAtt UserdetailsRepository.Arn

  UserdetailsRepositoryName:
    Description: The ECR repository ARN for the userdetails service
    Value: !Ref UserdetailsRepository

  UserdetailsRepositoryUri:
    Description: The ECR repository ARN for the userdetails service
    Value: !GetAtt UserdetailsRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-UserdetailsRepositoryUri

  UserdetailsSecret:
    Description: The Secrets name for userdetails
    Value: !Ref UserdetailsSecret

  UserdetailsRoleArn:
    Description: The name of the userdetails role
    Value: !GetAtt UserdetailsRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-UserdetailsRoleArn