apiVersion: v1
kind: Secret
metadata:
  name: userdetails-config-secret
  labels:
    {{- include "ala-userdetails.labels" . | nindent 4 }}
type: Opaque
data:
  userdetails-config.yaml: |
    {{ (.Files.Get "config/userdetails-config.yaml") | nindent 4 }}