version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      #  && curl -s "https://get.sdkman.io" | bash
      #  && chmod a+x /root/.sdkman/bin/sdkman-init.sh
      #  && source /root/.sdkman/bin/sdkman-init.sh && sdk install grails 6.0.0 /root/.sdkman/candidates/grails/6.0.0
      #  && apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      #  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      #  && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      #  && apt-get update
      #  && apt-get install -y docker-ce
      - apt-get install -y gradle
      - ./gradlew clean
      - ./gradlew assemble -Dorg.gradle.parallel=false

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the project...
      - ./gradlew build -Dorg.gradle.parallel=false
      - ./gradlew bootWar -Dorg.gradle.parallel=false

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
#      - aws s3 rm s3://ala-userdetails-builds/devbuilds/$CLEAN_BRANCH/ --recursive
#      - aws s3 cp build/libs/*.war s3://ala-userdetails-builds/devbuilds/$CLEAN_BRANCH/
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - rm -rf build/libs/*-plain.war
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME .
      - echo Tagging the Docker image...
      - echo tagging
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REPO:$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
      - docker push $ECR_REPO:$IMAGE_TAG