[DEFAULT]
PRODUCT_COMPONENT = base
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
BASE_STACK_FILE_PFIX = base
BASE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-${ENVIRONMENT}
AUTO_DEPLOY = false
SLACK_DEPLOY_NOTIFICATION = false
SLACK_CHANNEL = deployments
DEFAULT_LOGOUT_REDIRECT_URL = https://www.ala.org.au
APP_CLIENT_DOMAIN = ${PRODUCT_NAME}.${HOSTED_ZONE}

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-${CLEAN_BRANCH}
SLACK_DEPLOY_NOTIFICATION = true
SLACK_CHANNEL = zabbix-userdetails
AUTO_DEPLOY = true

APP_CLIENT_DOMAIN = ${PRODUCT_NAME}-${CLEAN_BRANCH}.${HOSTED_ZONE}
DEFAULT_LOGOUT_REDIRECT_URL = https://www-test.ala.org.au

[testing]
SLACK_DEPLOY_NOTIFICATION = true
SLACK_CHANNEL = zabbix-userdetails
AUTO_DEPLOY = true
DEFAULT_LOGOUT_REDIRECT_URL = https://www-test.ala.org.au

[staging]

[production]
