version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  exported-variables:
    - BUILD_IMAGE_TAG

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y gradle
      - ./gradlew clean
      - ./gradlew assemble -Dorg.gradle.parallel=false
      - echo Registering QEMU emulators for cross-platform builds...
      - docker run --rm --privileged public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v9.2.2 --install all
      - docker buildx version
      - docker buildx create --use --name multiarch-builder

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the project...
      - ./gradlew build -Dorg.gradle.parallel=false
      - ./gradlew bootWar -Dorg.gradle.parallel=false

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - rm -rf build/libs/*-plain.war
      - export BUILD_IMAGE_TAG=$CLEAN_BRANCH-$CODEBUILD_BUILD_NUMBER
      - echo "BUILD_IMAGE_TAG=$BUILD_IMAGE_TAG"
      - echo Building and pushing the multi-arch Docker image to ECR...
      - |
          docker buildx build --platform linux/amd64,linux/arm64 \
                              -f Dockerfile \
                              -t $ECR_REPO:$BUILD_IMAGE_TAG \
                              -t $ECR_REPO:$IMAGE_TAG \
                              --push \
                              .