[DEFAULT]
###
# pipeline vars
PRODUCT_COMPONENT = backend
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${ENVIRONMENT}
AUTO_DEPLOY = true
SLACK_DEPLOY_NOTIFICATION = false
SLACK_CHANNEL = deployments

###
# application vars
COGNITO_REGION = ap-southeast-2
AUTH_COOKIE_NAME = ALA-Auth
AUTH_COOKIE_ENABLED = true
OIDC_ENABLED = true
WEB_SERVICE_ENABLED = true
AUTH_COOKIE_DOMAIN = .ala.org.au
USERDETAILS_JWT_ENABLED = true
USERDETAILS_JWT_FALLBACK_TO_LEGACY = true
AFFILIATION_SURVEY = true
HEADER_AND_FOOTER_BASEURL = https://www.ala.org.au/commonui-bs5-2019
HEADER_AND_FOOTER_VERSION = 2
ENABLED_AUTHORISED_SYSTEMS = true
ENABLED_BULKCREATE = false
ENABLED_EXPORTUSERS = false
OPENAPI_SERVER_URLS = https://api.ala.org.au/userdetails/
TOKENAPP_URL =  https://tokens.ala.org.au/token
DOCSPORTAL_URL = https://docs.ala.org.au/#introduction
DEFAULT_LOGOUT_REDIRECT_URL = https://www.ala.org.au
DYNAMIC_CLIENT_TOKENS_CALLBACKURLS = ["https://tokens.ala.org.au/login"]
DYNAMODBTABLE_DYNAMODBPK = userId
DYNAMODBTABLE_DYNAMODBSK = clientId
APIKEY_ENABLED = true
APIKEY_AUTH_URL = https://auth.ala.org.au/apikey/ws/check/
APIKEY_CHECK_URL = https://auth.ala.org.au/apikey/ws/check?apikey=
APIKEY_USERDETAILS_URL = https://auth.ala.org.au/userdetails/userDetails/
DIGIVOL_ENABLED = true
SANDBOX_ENABLED = true
BIOCOLLECT_ENABLED = true

SIGHTINGS_URL = https://biocollect.ala.org.au/spotter
SPATIAL_URL = https://spatial.ala.org.au?tool=log
VOLUNTEER_URL = https://volunteer.ala.org.au/user/myStats
LISTS_URL = https://lists.ala.org.au/speciesList/list
BIOCACHE_SEARCH_BASE_URL = https://biocache.ala.org.au/occurrences/search
BIOCACHE_SEARCH_URL = "https://biocache.ala.org.au/occurrences/search/?q=*%3A*&fq=assertion_user_id%3A"
BIOCACHE_DOWNLOAD_URL = https://biocache.ala.org.au/download/myDownloads/
MYDATA_URL = https://sandbox.ala.org.au/tempDataResource/myData
ALERTS_URL = https://alerts.ala.org.au
ALA_BASE_URL = https://www.ala.org.au
BIE_BASE_URL =  https://bie.ala.org.au
SANDBOX_BASE_URL =  https://sandbox.ala.org.au

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
BASE_STACK_NAME = ala-${PRODUCT_NAME}-base-${CLEAN_BRANCH}
SLACK_CHANNEL = zabbix-userdetails
SUB_DOMAIN = ${PRODUCT_NAME}-${CLEAN_BRANCH}

###
# application vars
USERDETAILS_OIDC_LOGOUTURL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout
AUTH_COOKIE_NAME = ALA-Auth-Test
HEADER_AND_FOOTER_BASEURL = https://www.test.ala.org.au/commonui-bs5-2019
HEADER_AND_FOOTER_VERSION = 2
OPENAPI_SERVER_URLS = https://api.test.ala.org.au/userdetails/cognito/
OPENAPI_OAUTH_URL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/oauth2
GATEWAY_USAGEPLANID = yuz7fr
DYNAMIC_CLIENT_TOKENS_CALLBACKURLS = ["https://tokens.test.ala.org.au/login"]
TOKENAPP_URL =  https://tokens.test.ala.org.au/token
DOCSPORTAL_URL = https://docs.test.ala.org.au/#introduction
DYNAMODBTABLENAME = UserApplications-testing
#secrets are stored in secrets manager
RECAPTCHA_SITE_KEY = 6LcEpjglAAAAACBuI1AZ4CkJ4-NbxojpA7NaAgNN
FLICKR_KEY = 4e53956eac74ec2d14b40dd0291e630e
INATURALIST_KEY = 0f8d35e6bb4d612531b3535be3b42d1462564ceeb37e9fd44186361920f71650
APIKEY_AUTH_URL = https://auth-test.ala.org.au/apikey/ws/check/
APIKEY_CHECK_URL = https://auth-test.ala.org.au/apikey/ws/check?apikey=
APIKEY_USERDETAILS_URL = https://auth-test.ala.org.au/userdetails/userDetails/

SIGHTINGS_URL = https://biocollect-test.ala.org.au/spotter
SPATIAL_URL = https://spatial-test.ala.org.au?tool=log
VOLUNTEER_URL = https://digivol-uat.ala.org.au/user/myStats
LISTS_URL = https://lists-test.ala.org.au/speciesList/list
BIOCACHE_SEARCH_BASE_URL = https://biocache-test.ala.org.au/occurrences/search
BIOCACHE_SEARCH_URL = "https://biocache-test.ala.org.au/occurrences/search/?q=*%3A*&fq=assertion_user_id%3A"
BIOCACHE_DOWNLOAD_URL = https://biocache-test.ala.org.au/download/myDownloads/
MYDATA_URL = https://sandbox.ala.org.au/tempDataResource/myData
ALERTS_URL = https://alerts.test.ala.org.au
ALA_BASE_URL = https://www-test.ala.org.au
BIE_BASE_URL =  https://bie-test.ala.org.au
SANDBOX_BASE_URL =  https://sandbox.ala.org.au
DEFAULT_LOGOUT_REDIRECT_URL = https://www-test.ala.org.au

[testing]
SUB_DOMAIN = ${PRODUCT_NAME}
EKS_NAMESPACE = testing

###
# application vars
USERDETAILS_OIDC_LOGOUTURL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout
AUTH_COOKIE_NAME = ALA-Auth-Test
HEADER_AND_FOOTER_BASEURL = https://www.test.ala.org.au/commonui-bs5-2019
HEADER_AND_FOOTER_VERSION = 2
OPENAPI_SERVER_URLS = https://api.test.ala.org.au/userdetails/cognito/
OPENAPI_OAUTH_URL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/oauth2
GATEWAY_USAGEPLANID = yuz7fr
DYNAMIC_CLIENT_TOKENS_CALLBACKURLS = ["https://tokens.test.ala.org.au/login"]
TOKENAPP_URL =  https://tokens.test.ala.org.au/token
DOCSPORTAL_URL = https://docs.test.ala.org.au/#introduction
DYNAMODBTABLENAME = UserApplications-testing
#secrets are stored in secrets manager
RECAPTCHA_SITE_KEY = 6LdmofAqAAAAAJzdcJW5g40dygSM2PjZJSn9K52p
FLICKR_KEY = 4e53956eac74ec2d14b40dd0291e630e
INATURALIST_KEY = 0f8d35e6bb4d612531b3535be3b42d1462564ceeb37e9fd44186361920f71650
APIKEY_AUTH_URL = https://auth-test.ala.org.au/apikey/ws/check/
APIKEY_CHECK_URL = https://auth-test.ala.org.au/apikey/ws/check?apikey=
APIKEY_USERDETAILS_URL = https://auth-test.ala.org.au/userdetails/userDetails/

SIGHTINGS_URL = https://biocollect-test.ala.org.au/spotter
SPATIAL_URL = https://spatial-test.ala.org.au?tool=log
VOLUNTEER_URL = https://digivol-uat.ala.org.au/user/myStats
LISTS_URL = https://lists-test.ala.org.au/speciesList/list
BIOCACHE_SEARCH_BASE_URL = https://biocache-test.ala.org.au/occurrences/search
BIOCACHE_SEARCH_URL = "https://biocache-test.ala.org.au/occurrences/search/?q=*%3A*&fq=assertion_user_id%3A"
BIOCACHE_DOWNLOAD_URL = https://biocache-test.ala.org.au/download/myDownloads/
MYDATA_URL = https://sandbox.ala.org.au/tempDataResource/myData
ALERTS_URL = https://alerts.test.ala.org.au
ALA_BASE_URL = https://www-test.ala.org.au
BIE_BASE_URL =  https://bie-test.ala.org.au
SANDBOX_BASE_URL =  https://sandbox.ala.org.au
DEFAULT_LOGOUT_REDIRECT_URL = https://www-test.ala.org.au

[staging]
SUB_DOMAIN = ${PRODUCT_NAME}-staging

###
# application vars
USERDETAILS_OIDC_LOGOUTURL = https://auth-secure.ala.org.au/logout
OPENAPI_OAUTH_URL = https://auth-secure.ala.org.au/oauth2
GATEWAY_USAGEPLANID = j0fqm5
DYNAMODBTABLENAME = UserApplications-production
#secrets are stored in secrets manager
RECAPTCHA_SITE_KEY = 6LesDCEUAAAAABJrPrKq3Tfux5newwK8ThxDJrUv
FLICKR_KEY = 4e53956eac74ec2d14b40dd0291e630e
INATURALIST_KEY = 0f8d35e6bb4d612531b3535be3b42d1462564ceeb37e9fd44186361920f71650

[production]
SUB_DOMAIN = ${PRODUCT_NAME}
AUTO_DEPLOY = false
SLACK_DEPLOY_NOTIFICATION = true

###
# application vars
USERDETAILS_OIDC_LOGOUTURL = https://auth-secure.ala.org.au/logout
OPENAPI_OAUTH_URL = https://auth-secure.ala.org.au/oauth2
GATEWAY_USAGEPLANID = j0fqm5
DYNAMODBTABLENAME = UserApplications-production
#secrets are stored in secrets manager
RECAPTCHA_SITE_KEY = 6LesDCEUAAAAABJrPrKq3Tfux5newwK8ThxDJrUv
FLICKR_KEY = 4e53956eac74ec2d14b40dd0291e630e
INATURALIST_KEY = 0f8d35e6bb4d612531b3535be3b42d1462564ceeb37e9fd44186361920f71650