version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - env
      - cp $CODEBUILD_SRC_DIR_DeployConfigArtifact/helm/templates/configmap.yaml helm/templates/



  build:
    commands:
      - echo Build started on $(date)
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=$PRODUCT_NAME
      - printf "$(kubectl config current-context)\n"
      - eksctl create iamserviceaccount --name $SERVICE_ACCOUNT_NAME 
                                        --namespace $PRODUCT_NAME
                                        --cluster $EKS_CLUSTER_NAME 
                                        --attach-role-arn $USERDETAILS_ROLE_ARN
                                        --approve 
                                        --override-existing-serviceaccounts 
                                        --tags "product=$PRODUCT_NAME,environment=$ENVIRONMENT,branch=CLEAN_BRANCH"
      - cd helm
      - helm upgrade --install $IMAGE_NAME . 
                     -n $PRODUCT_NAME
                     --set image.repository=$ECR_REPO 
                     --set image.tag=$IMAGE_TAG 
                     --set ingress.hostname=$SUB_DOMAIN.$HOSTED_ZONE
                     --set ingress.certificateArn=$SSL_CERTIFICATE
                     --set aws.resourceTags.environment=$ENVIRONMENT
                     --set aws.resourceTags.product=$PRODUCT_NAME
                     --set aws.resourceTags.branch==$CLEAN_BRANCH
                     --set aws.resourceTags.component=helm


  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)