version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    OIDC_SECRET: $USERDETAILS_SECRET_NAME:userdetails_oidc_secret
    WEBSERVICE_SECRET: $USERDETAILS_SECRET_NAME:userdetails_webservice_secret
    $SECURITY_USER_PASSWORD: $USERDETAILS_SECRET_NAME:security_admin_password
    $FLICKR_SECRET: $USERDETAILS_SECRET_NAME:flickr_secret
    $INATURALIST_SECRET: $USERDETAILS_SECRET_NAME:inaturalist_secret
    $RECAPTCHA_SITE_SECRET: $USERDETAILS_SECRET_NAME:recaptcha_secret

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - echo copying configmap artifact
      - cp $CODEBUILD_SRC_DIR_ExportConfigArtifact/app.env app.env

  build:
    commands:
      - echo Build started on $(date)
      - echo $OIDC_SECRET
      - echo $FLICKR_SECRET
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=$PRODUCT_NAME
      - printf "$(kubectl config current-context)\n"
      - eksctl create iamserviceaccount --name $SERVICE_ACCOUNT_NAME 
                                        --namespace $PRODUCT_NAME
                                        --cluster $EKS_CLUSTER_NAME 
                                        --attach-role-arn $USERDETAILS_ROLE_ARN
                                        --approve 
                                        --override-existing-serviceaccounts 
                                        --tags "product=$PRODUCT_NAME,environment=$ENVIRONMENT,branch=CLEAN_BRANCH"
      - cd helm
      - |
        echo "
        app:
          url: https://$SUB_DOMAIN.$HOSTED_ZONE
        authCookieName: $AUTH_COOKIE_NAME
        defaultLogoutRedirectUri: $DEFAULT_LOGOUT_REDIRECT_URL
        affiliation:
          enabled: $AFFILIATION_SURVEY
        cookie:
          enabled: $AUTH_COOKIE_ENABLED
          domain: $AUTH_COOKIE_DOMAIN
        oauth2:
          baseUrl: $OPENAPI_OAUTH_URL
        oidc:
          enabled: $OIDC_ENABLED
          discoveryUri: $OIDC_DISCOVERY_URI
          clientId: $OIDC_CLIENT_ID
          logoutUrl: $USERDETAILS_OIDC_LOGOUTURL
          secret: $OIDC_SECRET
        jwt:
          enabled: $USERDETAILS_JWT_ENABLED
          legacy:
            enabled: $USERDETAILS_JWT_FALLBACK_TO_LEGACY
        webservice:
          enabled: $WEB_SERVICE_ENABLED
          clientId: $WEBSERVICE_CLIENT_ID
          clientSecret: $WEBSERVICE_SECRET
        apikey:
          enabled: $APIKEY_ENABLED
          auth:
            serviceUrl: $APIKEY_AUTH_URL
          check:
            serviceUrl: $APIKEY_CHECK_URL
          userdetails:
            serviceUrl: $APIKEY_USERDETAILS_URL
        security:
          user:
            password: $SECURITY_USER_PASSWORD
        aws:
          region: $COGNITO_REGION
          poolId: $COGNITO_POOLID
          usagePlanId: $GATEWAY_USAGEPLANID
        tokenApp:
          url: $TOKENAPP_URL
          callbackURLs: $DYNAMIC_CLIENT_TOKENS_CALLBACKURLS
        docsPortal:
          url: $DOCSPORTAL_URL
        dynamoDBTableName: $DYNAMODBTABLENAME
        userdetails:
          api:
            url: $OPENAPI_SERVER_URLS
        delegatedGroupNames: $USERS_DELEGATED_GROUP_NAMES
        flickr:
          key: $FLICKR_KEY
          secret: $FLICKR_SECRET
        inat:
          key: $INATURALIST_KEY
          secret: $INATURALIST_SECRET
        recaptcha:
          key: $RECAPTCHA_SITE_KEY
          secret: $RECAPTCHA_SITE_SECRET
        authorisedSystems:
          enabled: $ENABLED_AUTHORISED_SYSTEMS
        bulkCreate:
          enabled: $ENABLED_BULKCREATE
        exportUsers:
          enabled: $ENABLED_EXPORTUSERS
        myProfile:
          useDigiVol: $DIGIVOL_ENABLED
          useSandbox: $SANDBOX_ENABLED
          useBiocollect: $BIOCOLLECT_ENABLED
        headerAndFooter:
          baseURL: $HEADER_AND_FOOTER_BASEURL
          version: $HEADER_AND_FOOTER_VERSION
        sightings:
          url: $SIGHTINGS_URL
        spatial:
          url: $SPATIAL_URL
        volunteer:
          url: $VOLUNTEER_URL
        lists:
          url: $LISTS_URL
        biocache:
          search:
            baseUrl: $BIOCACHE_SEARCH_BASE_URL
            url: $BIOCACHE_SEARCH_URL
          myDownloads:
            url: $BIOCACHE_DOWNLOAD_URL
        myData:
          url: $MYDATA_URL
        alerts:
          url: $ALERTS_URL
        ala:
          baseURL: $ALA_BASE_URL
        bie:
          baseURL: $BIE_BASE_URL" > helm_values.yaml
      - echo helm values
      - cat helm_values.yaml
      - helm upgrade --install $IMAGE_NAME . 
                     -n $PRODUCT_NAME
                     --set image.repository=$ECR_REPO 
                     --set image.tag=$IMAGE_TAG 
                     --set ingress.hostname=$SUB_DOMAIN.$HOSTED_ZONE
                     --set ingress.certificateArn=$SSL_CERTIFICATE
                     --set aws.resourceTags.environment=$ENVIRONMENT
                     --set aws.resourceTags.product=$PRODUCT_NAME
                     --set aws.resourceTags.branch==$CLEAN_BRANCH
                     --set aws.resourceTags.component=helm
                     -f helm_values.yaml
                     --set deploymentAnnotations.checksum/configs="$(md5sum helm_values.yaml | awk '{print $1}')"
                     --set deploymentAnnotations.commitHash=$CODEBUILD_RESOLVED_SOURCE_VERSION


  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)