version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
#  secrets-manager:

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt update -y
        && cat /etc/lsb-release
        && apt-get -q -y install openjdk-11-jdk
        && apt-get -q -y install unzip
        && apt-get -q -y install zip
        && apt-get -q -y install curl
        && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        && apt-get update
        && apt-get install -y docker-ce
        && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        && chmod 700 get_helm.sh
        && ./get_helm.sh
        && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        && chmod +x kubectl
        && mv kubectl /usr/local/bin/
        && ARCH=amd64
        && PLATFORM=$(uname -s)_$ARCH
        && curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
        && tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
        && mv /tmp/eksctl /usr/local/bin

  build:
    commands:
      - echo Build started on $(date)
      - aws eks --region $REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - export REPO=$(aws cloudformation list-exports --query "Exports[?Name=='$BASE_STACK_NAME-UserdetailsRepositoryUri'].Value" --output text)
      - kubectl config set-context --current --namespace=$PRODUCT_NAME
      - printf "$(kubectl config current-context)\n"
      - export USERDETAILS_ROLE_ARN=$(aws cloudformation list-exports --query "Exports[?Name=='$BASE_STACK_NAME-UserdetailsRoleArn'].Value" --output text)
      - eksctl create iamserviceaccount --name userdetails-service-account 
                                        --namespace $PRODUCT_NAME 
                                        --cluster $EKS_CLUSTER_NAME 
                                        --role-name $USERDETAILS_ROLE_NAME
                                        --attach-role-arn $USERDETAILS_ROLE_ARN
                                        --approve 
                                        --override-existing-serviceaccounts 
                                        --tags "product=$PRODUCT_NAME,environment=$ENVIRONMENT,branch=${CLEAN_BRANCH}"
      - cd helm
      - helm upgrade --install $IMAGE_NAME . 
                     -n $PRODUCT_NAME 
                     --set image.repository=$REPO 
                     --set image.tag=$IMAGE_TAG 
                     --set ingress.hostname=$SUB_DOMAIN.$HOSTED_ZONE
                     --set ingress.certificateArn=$SSL_CERTIFICATE

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
