version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh

  build:
    commands:
      - echo Teardown started on $(date)
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl config set-context --current --namespace=$PRODUCT_NAME
      - printf "$(kubectl config current-context)\n"
      - eksctl delete iamserviceaccount
                  --name $SERVICE_ACCOUNT_NAME
                  --cluster $EKS_CLUSTER_NAME
      - cd helm
      - helm uninstall $IMAGE_NAME
               --timeout 900
               --wait


  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
