//import static org.springframework.boot.gradle.SpringBootPluginExtension.LayoutType.*

plugins {
    id "groovy"
    id "org.apache.grails.gradle.grails-web"
    id "org.apache.grails.gradle.grails-gsp"
    id "war"
    id "idea"
    id "cloud.wondrify.asset-pipeline"
    id "application"
    id "eclipse"

    id "maven-publish"
    id "com.gorylenko.gradle-git-properties" version "2.4.1"
}


repositories {
    mavenLocal()
    maven { url "https://nexus.ala.org.au/content/groups/public/" }
    maven { url "https://repo.grails.org/grails/core" }
    mavenCentral()
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

//grails {
//    plugins {
//        compile project(':openapi-plugin')
//    }
//}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    exclude group: 'org.apache.grails', module: 'grails-shell-cli'
}

dependencies {
    implementation("org.apache.grails:grails-core")
    implementation("org.apache.grails:grails-logging")
    implementation("org.apache.grails:grails-databinding")
    implementation("org.apache.grails:grails-interceptors")
    implementation("org.apache.grails:grails-rest-transforms")
    implementation("org.apache.grails:grails-services")
    implementation("org.apache.grails:grails-url-mappings")
    implementation("org.apache.grails:grails-web-boot")
    implementation("org.apache.grails:grails-gsp")
//    implementation("org.grails.plugins:hibernate5")
    implementation("org.apache.grails:grails-scaffolding")
    implementation("org.springframework.boot:spring-boot-autoconfigure")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-logging")
    implementation("org.springframework.boot:spring-boot-starter-tomcat")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("au.org.ala:ala-mail:3.0.0-SNAPSHOT")
    implementation("org.grails.plugins:grails-mail:5.0.3")
    runtimeOnly("javax.servlet:javax.servlet-api:4.0.1")
    runtimeOnly("org.grails:grails-web-sitemesh:6.2.3") {
        transitive = false
    }
    console("org.apache.grails:grails-console")
    runtimeOnly("cloud.wondrify:asset-pipeline-grails")
//    runtimeOnly("com.h2database:h2")
//    runtimeOnly("org.apache.tomcat:tomcat-jdbc")
    runtimeOnly("org.fusesource.jansi:jansi:1.18")
    testImplementation("org.apache.grails:grails-testing-support-datamapping")
    testImplementation("org.apache.grails:grails-testing-support-web")
    testImplementation("org.apache.grails:grails-geb")
    testImplementation("org.seleniumhq.selenium:selenium-api:4.19.1")
    testImplementation("org.seleniumhq.selenium:selenium-remote-driver:4.19.1")
    testImplementation("org.seleniumhq.selenium:selenium-support:4.19.1")
    testImplementation("org.spockframework:spock-core")
    testRuntimeOnly("org.seleniumhq.selenium:selenium-chrome-driver:4.19.1")
    testRuntimeOnly("org.seleniumhq.selenium:selenium-firefox-driver:4.19.1")
    testRuntimeOnly("org.seleniumhq.selenium:selenium-safari-driver:4.19.1")
    testImplementation("io.micronaut:micronaut-http-client")

    // regular JAR dependencies

    implementation platform('software.amazon.awssdk:bom:2.33.4')
    implementation 'software.amazon.awssdk:cognitoidentity'
    implementation 'software.amazon.awssdk:cognitoidentityprovider'
    implementation 'software.amazon.awssdk:dynamodb'
    implementation 'software.amazon.awssdk:sts'

}

grails {
    plugins {
        implementation project(':userdetails-plugin')
    }
}

application {
    mainClass.set("au.org.ala.userdetails.cognito.Application")
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperty "geb.env", System.getProperty('geb.env')
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")
    systemProperty 'webdriver.chrome.driver', "${System.getenv('CHROMEWEBDRIVER')}/chromedriver"
    systemProperty 'webdriver.gecko.driver', "${System.getenv('GECKOWEBDRIVER')}/geckodriver"
}
assets {
    minifyJs = true
    minifyCss = true
}

springBoot {
    buildInfo()
}

bootRun {
    ignoreExitValue true
    jvmArgs(
            '-Dspring.output.ansi.enabled=always',
            '-noverify',
            '-XX:TieredStopAtLevel=1',
            '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

bootWar {
    launchScript()
    archiveClassifier = 'exec'
}



publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        mavenJar(MavenPublication) {
            artifact bootWar
        }
    }
}
